return {}
-- return {
--   {
--     "mason-org/mason-lspconfig.nvim",
--     opts = {
--     },
--     dependencies = {
--       { "mason-org/mason.nvim", opts = {}, config = function()
--         require("mason").setup()
--       end
--       },
--       "neovim/nvim-lspconfig",
--     },
--     config = function()
--       automatic_enable = false
--     end,
--   },
--   {
--     "neovim/nvim-lspconfig",
--     lazy = false,
--     config = function()
--       local capabilities = require('cmp_nvim_lsp').default_capabilities()
--
--       local lspconfig = require("lspconfig")
--       lspconfig.tsserver.setup({
--         capabilities = capabilities
--       })
--       lspconfig.solargraph.setup({
--         capabilities = capabilities
--       })
--       lspconfig.html.setup({
--         capabilities = capabilities
--       })
--       lspconfig.lua_ls.setup({
--         capabilities = capabilities
--       })
--
--       vim.keymap.set("n", "K", vim.lsp.buf.hover, {})
--       vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, {})
--       vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, {})
--       vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, {})
--     end,
--   }
-- }
